Contenido bajo licencia Creative Commons BY-NC-ND. El contenido de este Notebook es creado por Ana Beatriz Acevedo Jaramillo y Daniela González González 2020. Este material es parte del curso Análisis de Estructuras del programa de Ingeniería Civil de la Universidad EAFIT.

<img src= 
"http://www.eafit.edu.co/biblioteca/PublishingImages/logos/eafit_apa.jpg" 
         alt="GeeksforGeeks logo" 
         align="left">

# *Análisis matricial de cerchas planas*

<p style='text-align: justify;'> Este Notebook fue desarrollado como parte del material de apoyo para realizar el análisis de cerchas planas. Debe tener en cuenta que los datos de entrada que aparecen por defecto corresponden al ejercicio explicado en el documento que acompaña a este Notebook.</p>

## DATOS DE ENTRADA

<p style='text-align: justify;'> Esta sección contiene los datos que debe ingresar el usuario para que el Notebook realice en ánalisis de la estructura.</p>

In [1]:
import numpy as np
import pandas as pd

### Información general de la estructura: 

In [2]:
Nn=4 #Número de nodos    
Ne=5 #Número de elementos   
NGLL=5 #Número de grados de libertad libres

Con la información anterior se cálcula lo siguiente:

In [3]:
NGL=2*Nn #Cálculo del número de grados de libertad
NGLR=NGL-NGLL #Cálculo del número de grados de libertad restringidos

### Grados de libertad asociados a cada elemento:


$$
\begin{align}
MGL = \\
\end{align} 
\begin{bmatrix}
gxi_{0} &gyi_{0} &gxf_{0} &gyf_{0}\\
gxi_{1} &gyi_{1} &gxf_{1} &gyf_{1}\\
gxi_{2} &gyi_{2} &gxf_{2} &gyf_{2}\\
. &. &. &.\\
gxi_{n} &gyi_{n} &gxf_{n} &gyf_{n}\end{bmatrix}\, .$$


In [4]:
MGL=[[6,7,2,3],[2,3,4,5],[6,7,0,1],[0,1,4,5],[0,1,2,3]] #Matriz con información de los grados de libertad asociados a cada elemento

### Propiedades de los elementos: 

|MA|ME|
|:-:|:-:|
|$$
\begin{align}
\\
\end{align} 
\begin{bmatrix}
A_{0}\\A_{1}\\A_{2}\\.\\A_{n}\end{bmatrix}\, $$|$$
\begin{align}
\\
\end{align} 
\begin{bmatrix}
E_{0}\\E_{1}\\E_{2}\\.\\E_{n}\end{bmatrix}\, $$|
                


In [5]:
MA=[[750],[750],[1000],[1000],[750]] #Matriz con las áreas de la sección transversal de cada elemento (en mm2).
ME=[[200],[200],[200],[200],[200]] #Matriz con el módulo de elasticidad de cada elemento (en GPa).

### Coordenadas de los nodos iniciales y finales de los elementos:

$$
\begin{align}
MC = \\
\end{align} 
\begin{bmatrix}
xi_{0} &yi_{0} &xf_{0} &yf_{0}\\
xi_{1} &yi_{1} &xf_{1} &yf_{1}\\
xi_{2} &yi_{2} &xf_{2} &yf_{2}\\
. &. &. &.\\
xi_{n} &yi_{n} &xf_{n} &yf_{n}\end{bmatrix}\, .$$


In [6]:
MC=[[0,0,4000,3000],[4000,3000,8000,0],[0,0,4000,0],[4000,0,8000,0],[4000,0,4000,3000]] #Matriz que almacena las coordenadas de los nodos iniciales y finales de cada elemento (en mm).

### Cargas aplicadas en los nodos: 

In [7]:
F0=[[0],[-10],[0],[0],[20]] #Matriz de fuerzas aplicadas en los grados de libertad libres (en kN).

### Desplazamientos en los grados de libertad restringidos:

In [8]:
U1=[[0],[0],[0]] #Matriz de desplazamientos en los grados de libertad restringidos (en mm).

## CÁLCULO DE REACCIONES Y DESPLAZAMIENTOS DE LA CERCHA:

<p style='text-align: justify;'> En esta sección se procesan los datos ingresados para calcular las reacciones (fuerzas en los grados de libertad restringidos) y los desplazamientos de los grados de libertad libres.</p>

### Cálculo de longitudes de los elementos:

In [9]:
ML=np.zeros((Ne,1)) #Matriz de almacenamiento de longitudes
for i in range(Ne):
    ML[i,0]=np.sqrt((MC[i][2]-MC[i][0])**2+(MC[i][3]-MC[i][1])**2)
print(np.array(ML))
  

[[5000.]
 [5000.]
 [4000.]
 [4000.]
 [3000.]]


### Cálculo y almacenamiento de la matriz de rigidez local de los elementos:

In [10]:
MAL=np.zeros((Ne,4,4)) #Matriz de almacenamiento de matrices de rigidez en coordenadas locales
for i in range(Ne):
    MAL[i,0,0]=(MA[i][0]*ME[i][0])/(ML[i][0])
    MAL[i,0,2]=-MAL[i,0,0]
    MAL[i,2,0]=-MAL[i,0,0]
    MAL[i,2,2]=MAL[i,0,0]

<div class="alert alert-warning">

*Visualización de la matriz de rigidez local de un elemento de la cercha:*

Indique el número del elemento (n) para el cual desea ver la matriz de rigidez local.

</div>


In [11]:
n=0

In [12]:
df=pd.DataFrame(MAL[n])
df

0    1     2    3
0  30.0  0.0 -30.0  0.0
1   0.0  0.0   0.0  0.0
2 -30.0  0.0  30.0  0.0
3   0.0  0.0   0.0  0.0

### Cálculo de la matriz de transformación:

In [13]:
MAT=np.zeros((Ne,4,4)) #Matriz de almacenamiento de las matrices de transformación
for i in range(Ne):
    MAT[i,0,0]=(MC[i][2]-MC[i][0])/(ML[i][0])
    MAT[i,1,0]=(MC[i][3]-MC[i][1])/(ML[i][0])
    MAT[i,2,2]=MAT[i,0,0]
    MAT[i,3,2]=MAT[i,1,0]
            

<div class="alert alert-warning">

*Visualización de la matriz de transformación de un elemento de la cercha:*

Indique el número del elemento (n) para el cual desea ver la matriz de transformación.

</div>

In [14]:
n=0

In [15]:
df=pd.DataFrame(MAT[n])
df

0    1    2    3
0  0.8  0.0  0.0  0.0
1  0.6  0.0  0.0  0.0
2  0.0  0.0  0.8  0.0
3  0.0  0.0  0.6  0.0

### Cálculo de la matriz de rigidez de cada elemento en coordenadas globales:

In [16]:
MAG=np.zeros((Ne,4,4)) #Matriz de almacenamiento de las matrices de rigidez en coordenadas globales
for i in range(Ne):
    MAG[i]=np.dot(np.dot(MAT[i],MAL[i]),np.transpose(MAT[i]))  

<div class="alert alert-warning">

*Visualización de la matriz de rigidez global de un elemento de la cercha:*

Indique el número del elemento (n) para el cual desea ver la matriz de rigidez global.

</div>

In [17]:
n=0

In [18]:
df=pd.DataFrame(MAG[n])
df

0     1     2     3
0  19.2  14.4 -19.2 -14.4
1  14.4  10.8 -14.4 -10.8
2 -19.2 -14.4  19.2  14.4
3 -14.4 -10.8  14.4  10.8

### Cálculo de la matriz de rigidez de la estructura:

In [19]:
KG=np.zeros((NGL,NGL)) #Matriz de rigidez global de la estructura
for i in range(Ne):
    for j in range(4):
        for k in range(4):
            KG[int(MGL[i][k]),int(MGL[i][j])]=KG[int(MGL[i][k])][int(MGL[i][j])]+MAG[i][j][k]

In [20]:
df=pd.DataFrame(KG)
df

0     1     2     3     4     5     6     7
0  100.0   0.0   0.0   0.0 -50.0   0.0 -50.0   0.0
1    0.0  50.0   0.0 -50.0   0.0   0.0   0.0   0.0
2    0.0   0.0  38.4   0.0 -19.2  14.4 -19.2 -14.4
3    0.0 -50.0   0.0  71.6  14.4 -10.8 -14.4 -10.8
4  -50.0   0.0 -19.2  14.4  69.2 -14.4   0.0   0.0
5    0.0   0.0  14.4 -10.8 -14.4  10.8   0.0   0.0
6  -50.0   0.0 -19.2 -14.4   0.0   0.0  69.2  14.4
7    0.0   0.0 -14.4 -10.8   0.0   0.0  14.4  10.8

### Subdivisión de la matriz de rigidez global de la estructura:

In [21]:
K0 = KG[0:NGLL,0:NGLL]
K1 = KG[0:NGLL,NGLL:NGL]
K2 = KG[NGLL:NGL,0:NGLL]
K3 = KG[NGLL:NGL,NGLL:NGL]  

### Cálculo de desplazamientos:


In [22]:
Feff=F0-np.dot(K1,U1)
U0=np.dot((np.linalg.inv(K0)),Feff) #Desplazamientos en los grados de libertad libres en mm    
print(np.array(U0))

[[ 0.53333333]
 [-1.37407407]
 [ 0.53333333]
 [-1.17407407]
 [ 1.06666667]]


### Cálculo de reacciones:

In [23]:
F1=np.dot(K2,U0)+np.dot(K3,U1) #Reacciones en kN (grados de libertad restringidos)
print(np.array(F1))

[[  5.]
 [-20.]
 [  5.]]


## CÁLCULO DE LAS FUERZAS INTERNAS DE LA CERCHA:

<p style='text-align: justify;'> En esta sección se calcula la fuerza interna de cada elemento de la cercha.</p>

### Cálculo de las fuerzas de cada elemento en coodenadas globales:



In [24]:
U=np.concatenate((U0,U1)) #Matriz de desplazamientos de todos los grados de libertad
MU=np.zeros((Ne,4,1)) #Matriz de almacenamiento de vectores de desplazamiento de cada elemento
for i in range(Ne):
    for j in range(4):
        MU[i,j,0]=U[int(MGL[i][j])][0]

<div class="alert alert-warning">

*Visualización de los desplazamientos de un elemento de la cercha:*

Indique el número del elemento (n) para el cual desea ver los desplazamientos.

</div>

In [25]:
n=0

In [26]:
print(np.array(MU[n]))

[[ 0.        ]
 [ 0.        ]
 [ 0.53333333]
 [-1.17407407]]


In [27]:
MFG=np.zeros((Ne,4,1)) #Matriz de almacenamiento de las fuerzas de cada elemento en coordenadas globales
for i in range(Ne):
    MFG[i]=np.dot(MAG[i],MU[i])

<div class="alert alert-warning">

*Visualización de las fuerzas en coordenadas globales de un elemento de la cercha:*

Indique el número del elemento (n) para el cual desea ver las fuerzas en coordenadas globales.

</div>

In [28]:
n=0

In [29]:
print(np.array(MFG[n]))

[[ 6.66666667]
 [ 5.        ]
 [-6.66666667]
 [-5.        ]]


### Cálculo de las fuerzas de cada elemento en coordenadas locales:

In [30]:
MFL=np.zeros((Ne,4,1)) #Matriz de almacenamiento de las fuerzas de cada elemento en coordenadas locales
for i in range(Ne):
    MFL[i]=np.dot(np.transpose(MAT[i]),MFG[i])

<div class="alert alert-warning">

*Visualización de las fuerzas en coordenadas locales de un elemento de la cercha:*

Indique el número del elemento (n) para el cual desea ver las fuerzas en coordenadas locales.

</div>

In [31]:
n=0

In [32]:
print(np.array(MFL[n]))

[[ 8.33333333]
 [ 0.        ]
 [-8.33333333]
 [ 0.        ]]


### Cálculo de las fuerzas internas de cada elemento:

In [33]:
FELEM=np.zeros((Ne,1)) #Matriz de almacenamiento de fuerzas internas
for i in range(Ne):
    FELEM[i,0]=-MFL[i,0,0]
print(np.array(FELEM))

[[-8.33333333]
 [-8.33333333]
 [26.66666667]
 [26.66666667]
 [10.        ]]
