Este material es parte del curso Análisis de Estruturas en el programa de Ingeniería Civil de la Universidad EAFIT. Fue preparado por Ana Beatriz Acevedo y Daniela Gonzalez.

# Cercha plana: matriz de rigidez global del elemento

## Matriz de rigidez local

Los parámetros que definen la matriz de rigidez de una cercha plana son (para cada elemento): Área de la sección transversal (A), módulo de rigidez (E) y longitud (L).

$$
k=\begin{bmatrix}
\frac{AE}{L} &0 &-\frac{AE}{L} &0\\
0 &0 &0 &0\\
-\frac{AE}{L} &0 &\frac{AE}{L} &0\\
0 &0 &0 &0
\end{bmatrix}
$$

Consideremos un elemento con estas propiedades: Área = 500 mm$^{2}$, Longitud = 2 m y E_acero = 200,000 MPa.

<div class="alert alert-warning">
Es muy importante ser consistentes con las unidades. Vamos a trabajar las fuerzas en kN y las distancias en mm.
</div>

Ingresa los valores de las propiedades de los elementos con estas unidades:

In [1]:
A = 500 #Área de la sección transversal en mm^2
L = 2000 #Longitud del elemento en m
E = 200 #Módulo de elasticidad en GPa

Generemos la matriz de rigidez del elemento kL (k en coordenadas locales). Las unidades son (kN/mm).

In [2]:
import numpy as np
MAL = np.zeros((4,4), dtype =float)
MAL[0,0]=A*E/L
MAL[2,0]=-A*E/L
MAL[0,2]=-A*E/L
MAL[2,2]=A*E/L
print(MAL)

[[ 50.   0. -50.   0.]
 [  0.   0.   0.   0.]
 [-50.   0.  50.   0.]
 [  0.   0.   0.   0.]]


Esta matriz es única para el elemento: *No importa la dirección del elemento, está siempre será su matriz*

**Modifica los valores de las propiedades de los elementos para ver sus efectos en la matriz de rigidez local**

## Matriz de transformación##

Ahora consideremos la posición del elemento en el espacio

<img src="img\Elemento_inclinado.PNG">
$$
\begin{Bmatrix} F_1\\ F_2\\ F_7\\ F_8\end{Bmatrix} =
\begin{bmatrix}
CX &0 &0 &0\\
CY &0 &0 &0\\
0 &0 &CX &0\\
0 &0 & CY &0\\
\end{bmatrix}
\begin{Bmatrix} f_1\\ f_1\\ f_2\\ f_9\end{Bmatrix}
$$


$$
\{F\}=\begin{bmatrix}T\end{bmatrix}*\{f\}
$$

$
\begin{bmatrix}T\end{bmatrix}=$ Matriz de transformación de coordenadas

Longitud del elemento: $L=\sqrt{(X_f-X_i)^{2}+(Y_f-Y_i)^{2}+(Z_f-Z_i)^{2}}$

$CX=\frac{X_f-X_i}{L}$; $CY=\frac{Y_f-Y_i}{L}$; $CZ=\frac{Z_f-Z_i}{L}$

Consideremos la cercha de acero de la figura. El área transversal de los elementos internos es de 550 mm$^{2}$ y de los elementos externos de 700 mm$^{2}. (E acero = 200,000 MPa = 200 GPa)

<img src="img\Cercha.PNG">

Los elementos AD y CF tienen igual área, igual longitud e igual módulo de elasticidad. Por lo tanto tienen igual matriz de rigidez local. **Calcula la matriz de rigidez local de los estos elementos**

In [3]:
A = 700 #Área de la sección transversal en mm`2
L = ((1.5**2+2.5**2)**0.5)*1000 #Longitud en mm
E = 200 #Módulo de elasticidad en GPa
MAL = np.zeros((4,4), dtype =float)
MAL[0,0]=A*E/L
MAL[2,0]=-A*E/L
MAL[0,2]=-A*E/L
MAL[2,2]=A*E/L
print(MAL)

[[ 48.01960384   0.         -48.01960384   0.        ]
 [  0.           0.           0.           0.        ]
 [-48.01960384   0.          48.01960384   0.        ]
 [  0.           0.           0.           0.        ]]


Calcula la matriz de transformación del elemento AD *Recuerda que estamos trabajando en mm y en kN*.

Primero calculemos los cosenos directores de AD:

In [4]:
CX=(1500-0)/L
CY=(0-2500)/L
print(CX)
print(CY)

0.5144957554275265
-0.8574929257125442


Ahora calculemos la matriz de transformación AD:

In [5]:
MT_AD = np.zeros((4,4), dtype =float)
MT_AD[0,0]=CX
MT_AD[1,0]=CY
MT_AD[2,2]=CX
MT_AD[3,2]=CY
print(MT_AD)

[[ 0.51449576  0.          0.          0.        ]
 [-0.85749293  0.          0.          0.        ]
 [ 0.          0.          0.51449576  0.        ]
 [ 0.          0.         -0.85749293  0.        ]]


Cambiemos de elemento. Ahora consideremos CF:

Cosenos directores:

In [6]:
CX=(4500-6000)/L
CY=(0-2500)/L
print(CX)
print(CY)

-0.5144957554275265
-0.8574929257125442


**¿Qué diferencia notas con respecto a los cosenos directores del elemento AD? ¿A qué se debe?**

Ahora calculemos la matriz de transformación de CF:

In [7]:
MT_CF = np.zeros((4,4), dtype =float)
MT_CF[0,0]=CX
MT_CF[1,0]=CY
MT_CF[2,2]=CX
MT_CF[3,2]=CY
print(MT_CF)

[[-0.51449576  0.          0.          0.        ]
 [-0.85749293  0.          0.          0.        ]
 [ 0.          0.         -0.51449576  0.        ]
 [ 0.          0.         -0.85749293  0.        ]]


**¿Por qué son diferentes?**

## Matriz del elemento en coordenadas globales##

$$
\begin{bmatrix}K\end{bmatrix}=\begin{bmatrix}T\end{bmatrix}*\begin{bmatrix}k\end{bmatrix}*\begin{bmatrix}T\end{bmatrix}^{-1}
$$



Calculemos ahora la matriz de rigidez de cada elemento en coordenadas globales

In [8]:
K_AD=np.dot(MT_AD,np.dot(MAL,np.transpose(MT_AD)))
print(K_AD)

[[ 12.7110716  -21.18511934 -12.7110716   21.18511934]
 [-21.18511934  35.30853224  21.18511934 -35.30853224]
 [-12.7110716   21.18511934  12.7110716  -21.18511934]
 [ 21.18511934 -35.30853224 -21.18511934  35.30853224]]


In [9]:
K_CF=np.dot(MT_CF,np.dot(MAL,np.transpose(MT_CF)))
print(K_CF)

[[ 12.7110716   21.18511934 -12.7110716  -21.18511934]
 [ 21.18511934  35.30853224 -21.18511934 -35.30853224]
 [-12.7110716  -21.18511934  12.7110716   21.18511934]
 [-21.18511934 -35.30853224  21.18511934  35.30853224]]


**¿Qué diferencias ves?, ¿A qué se deben?**