Este material es parte del curso Análisis de Estruturas en el programa de Ingeniería Civil de la Universidad EAFIT. Fue preparado por Ana Beatriz Acevedo y Daniela Gonzalez.

# Taller 2: Matriz de rigidez global de la estructura

Para la cercha a continuación calcular la matriz de rigidez global.

<img src="img\Cercha.PNG">

## Datos de entrada

Área transversal de los elementos internos ($A_i$) y de los elementos externos ($A_e$) en mm$^{2}$:

In [1]:
Ai = 
Ae = 

Determinar el número de nodos (Nn) y el número de elementos (Ne) que conforman la cercha:

In [2]:
Nn = 
Ne = 

In [3]:
NGL = 12

Enumerar los grados de libertad de cada nodo, teniendo en cuenta como sugerencia que los últimos grados de libertad enumerados corresponden a los desplazamientos conocidos.

In [4]:
Ax = 10
Ay = 9
Bx = 5
By = 6
Cx = 7
Cy = 8
Dx = 1
Dy = 2
Ex = 3
Ey = 4
Fx = 11
Fy = 12

In [6]:
import numpy as np
MGL = np.array([[10, 9, 5, 6],[5, 6, 7, 8], [1, 2, 3, 4], [3, 4, 11, 12],[3, 4, 5, 6],[1, 2, 10, 9],[1, 2, 5, 6], [11, 12, 5, 6], [11, 12, 7, 8]])

In [9]:
print (MGL)

[[10  9  5  6]
 [ 5  6  7  8]
 [ 1  2  3  4]
 [ 3  4 11 12]
 [ 3  4  5  6]
 [ 1  2 10  9]
 [ 1  2  5  6]
 [11 12  5  6]
 [11 12  7  8]]


Matriz con propiedades de cada elemento (MA):

In [11]:
MA = np.array([[Ae],[Ae],[Ae],[Ae],[Ai],[Ae],[Ai],[Ai],[Ae]])
print (MA)

[[700]
 [700]
 [700]
 [700]
 [550]
 [700]
 [550]
 [550]
 [700]]


Matriz con módulo de elasticidad

In [12]:
E = 200 #En GPA, E_acero = 200,00 MPA

In [13]:
ME = np.array([[E],[E],[E],[E],[E],[E],[E],[E],[E]])
print (ME)

[[200]
 [200]
 [200]
 [200]
 [200]
 [200]
 [200]
 [200]
 [200]]


Matriz con coordenadas iniciales y finales de cada elemento, ME, en mm

In [14]:
MC = np.array([[0, 2.5, 3, 2.5],[3, 2.5, 6, 2.5],[1.5, 0, 3, 0],[3, 0, 4.5, 0],[3, 0, 3, 2.5],[1.5, 0, 0, 2.5],[1.5, 0, 3, 2.5],[4.5, 0, 3, 2.5],[4.5, 0, 6, 2.5]]) # en m
MC= MC*1000 #en mm
print (MC)

[[   0. 2500. 3000. 2500.]
 [3000. 2500. 6000. 2500.]
 [1500.    0. 3000.    0.]
 [3000.    0. 4500.    0.]
 [3000.    0. 3000. 2500.]
 [1500.    0.    0. 2500.]
 [1500.    0. 3000. 2500.]
 [4500.    0. 3000. 2500.]
 [4500.    0. 6000. 2500.]]


<div class="alert alert-warning">
*Propuesta: crea un código que te permita dibujar la cercha. Así podrás darte cuenta si entraste bien los datos*
</div>

## Cálculos 

Calcular la matriz de longitudes de cada elemento ML:

In [15]:
ML = np.zeros((Ne,1),dtype=float) #matriz de almacenamiento, inicia en ceros
for i in range(Ne):
    ML[i,0]=((MC[i,2]-MC[i,0])**2+(MC[i,3]-MC[i,1])**2)**0.5
print (ML)

[[3000.        ]
 [3000.        ]
 [1500.        ]
 [1500.        ]
 [2500.        ]
 [2915.47594742]
 [2915.47594742]
 [2915.47594742]
 [2915.47594742]]


Matriz de rigidez local (MAL)

In [17]:
MAL=np.zeros((Ne,4,4),dtype=float)
for i in range (Ne):
    MAL[i,0,0]=(MA[i,0]*ME[i,0])/ML[i,0]
    MAL[i,0,2]=-MAL[i,0,0]
    MAL[i,2,0]=-MAL[i,0,0]
    MAL[i,2,2]=MAL[i,0,0]
print(MAL)

[[[ 46.66666667   0.         -46.66666667   0.        ]
  [  0.           0.           0.           0.        ]
  [-46.66666667   0.          46.66666667   0.        ]
  [  0.           0.           0.           0.        ]]

 [[ 46.66666667   0.         -46.66666667   0.        ]
  [  0.           0.           0.           0.        ]
  [-46.66666667   0.          46.66666667   0.        ]
  [  0.           0.           0.           0.        ]]

 [[ 93.33333333   0.         -93.33333333   0.        ]
  [  0.           0.           0.           0.        ]
  [-93.33333333   0.          93.33333333   0.        ]
  [  0.           0.           0.           0.        ]]

 [[ 93.33333333   0.         -93.33333333   0.        ]
  [  0.           0.           0.           0.        ]
  [-93.33333333   0.          93.33333333   0.        ]
  [  0.           0.           0.           0.        ]]

 [[ 44.           0.         -44.           0.        ]
  [  0.           0.           0.       

Matriz de transformación (MAT). Matriz tridimensional de matrices de transformación de cada elemento.

In [18]:
MAT=np.zeros((Ne,4,4),dtype=float)
for i in range (Ne):
    MAT[i,0,0]=(MC[i,2]-MC[i,0])/ML[i,0]
    MAT[i,1,0]=(MC[i,3]-MC[i,1])/ML[i,0]
    MAT[i,2,2]=MAT[i,0,0]
    MAT[i,3,2]=MAT[i,1,0]
print(MAT)

[[[ 1.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          1.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 1.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          1.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 1.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          1.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 1.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          1.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 1.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 

Cálculo de la matriz de rigidez en coordenadas globales de cada elemento en [kN/mm]. MAG:

In [19]:
MAG=np.zeros((Ne,4,4),dtype=float)
for i in range (Ne):
    MAG[i]=np.dot(MAT[i],np.dot(MAL[i],np.transpose(MAT[i])))
print(MAG)

[[[ 46.66666667   0.         -46.66666667   0.        ]
  [  0.           0.           0.           0.        ]
  [-46.66666667   0.          46.66666667   0.        ]
  [  0.           0.           0.           0.        ]]

 [[ 46.66666667   0.         -46.66666667   0.        ]
  [  0.           0.           0.           0.        ]
  [-46.66666667   0.          46.66666667   0.        ]
  [  0.           0.           0.           0.        ]]

 [[ 93.33333333   0.         -93.33333333   0.        ]
  [  0.           0.           0.           0.        ]
  [-93.33333333   0.          93.33333333   0.        ]
  [  0.           0.           0.           0.        ]]

 [[ 93.33333333   0.         -93.33333333   0.        ]
  [  0.           0.           0.           0.        ]
  [-93.33333333   0.          93.33333333   0.        ]
  [  0.           0.           0.           0.        ]]

 [[  0.           0.           0.           0.        ]
  [  0.          44.           0.       

## Ensamble de la matriz de rigidez global

Matriz de rigidez global de la estructura KG:
¿Cuál es el tamaño de la matriz de rigidez global?

In [22]:
KG=np.zeros((NGL,NGL),dtype=float)
for i in range (Ne):
    for j in range (4):
        for k in range (4):
            KG[MGL[i,j]-1,MGL[i,k]-1]=KG[MGL[i,j]-1,MGL[i,k]-1]+MAG[i,j,k]
print(KG)

[[116.03167548  -4.53966843 -93.33333333   0.          -9.98727055
  -16.64545091   0.           0.          21.18511934 -12.7110716
    0.           0.        ]
 [ -4.53966843  63.05095042   0.           0.         -16.64545091
  -27.74241818   0.           0.         -35.30853224  21.18511934
    0.           0.        ]
 [-93.33333333   0.         186.66666667   0.           0.
    0.           0.           0.           0.           0.
  -93.33333333   0.        ]
 [  0.           0.           0.          44.           0.
  -44.           0.           0.           0.           0.
    0.           0.        ]
 [ -9.98727055 -16.64545091   0.           0.         113.30787443
    0.         -46.66666667   0.           0.         -46.66666667
   -9.98727055  16.64545091]
 [-16.64545091 -27.74241818   0.         -44.           0.
   99.48483637   0.           0.           0.           0.
   16.64545091 -27.74241818]
 [  0.           0.           0.           0.         -46.66666667
    